spring:
  profiles: local
  datasource:
    url: jdbc:postgresql://localhost:55432/kotlink
    username: ktuser
    password: ktpass
  thymeleaf:
    cache: false

logging:
  level:
    org.springframework.web.servlet: INFO
    Exposed: DEBUG