apiVersion: v1
kind: Secret
metadata:
  name: kotlink
type: Opaque
stringData:
  google_oauth_client_id: 115327279391-cqrf3suvt416skdkr8lqvdntgfa90epg.apps.googleusercontent.com
  google_oauth_client_secret: SZDICodbaLAkNXjbFKfOFZCO
  spring_datasource_url: jdbc:postgresql://postgres:5432/kotlink?useSSL=false&connectTimeout=3&socketTimeout=3
  spring_datasource_username: kotlinkuser
  spring_datasource_password: kotlinkpass
  actuator_user_name: kotlink_actuator
  actuator_user_password: kotlink_actuator